name: gnostr

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  gnostr:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install cargo-binstall
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

    - name: Install gnostr
      run: cargo binstall gnostr --no-confirm
